### ISSUE TITLE
Submitting a rewritten branch creates a new review

### ISSUE THREAD

**Issue by afranke** [google/git-appraise#55]
I have submitted a first version of my branch for review, the review was rejected because I needed to fix something. I fixed what I was asked to, used commit --amend, and submitted again. Instead of reusing the existing (rejected) review and appending to the discussion, it created a brand new review as if the first one didn't exist, thus losing history.

**Comment by ojarjur** [comment]
First off, thanks for trying out the tool and providing feedback.

The behavior your are seeing is intentional (as opposed to being a bug that slipped through), but I agree that there is a lot of room for improvement.

Things get complicated because sometimes you actually do want to throw away the old review and create a new one. However, as you mentioned, at other times you just want to continue the review at a different starting commit.

Right now we only support the first option, but want to support both. Issue #45 lays out the current plan of record in this regard.

However, even once we do finish the work in #45, the default will continue to be creating a new review, as:

* That more closely follows the semantics of the corresponding git command (e.g. the goal of running `git commit --amend` is to get rid of the previous version of the commit).

and

* 'git-appraise' has to be told about the rewrite in order to know that the two reviews need to be linked.

So, to rewrite the commit while continuing the current review, you'll have to run something like `git appraise rebase` rather than just `git commit --amend`.

**Comment by ojarjur** [comment]
FYI, I'll keep this open until #45 is closed, but most of the discussion will happen in that issue instead of this one.
