### ISSUE TITLE
Github integration?

### ISSUE THREAD

**Issue by cdrage** [google/git-appraise#7]
Bit of an odd question.

I've been using "ghi" for a majority of my time on github, with the inclusion of it's experimental PR for reviewing and accepting PR's. See https://github.com/stephencelis/ghi

Now I've seen git-appraise and it fits (mostly) into what I've been looking at for reviewing PR requests on the command line without having to jump through hoops in a web-interface.

Would you be open for plugin-like contributions (for example, connecting to the Github API for reading comments on GHI requests, giving your praise, etc.). 

Eventually Gitlab integration, gogs (https://github.com/gogits/gogs), etc. So having more than one option for just Github would be great.

I don't have a general outline yet, but thought I'd throw it up in the air.

**Comment by ojarjur** [comment]
Thanks for reaching out. We're definitely open to integration with other tools.

From the perspective of git-appraise, these would not be "plugins" in the traditional sense, since they would not be run by the git-appraise tool. Rather, there are two ways that another tool can be integrated:
    1. Directly reading and writing the formats as specified in the README.md file. There are [Eclipse](https://github.com/google/git-appraise-eclipse) and [Jenkins](https://github.com/jenkinsci/google-git-notes-publisher-plugin) plugins that both follow this model.
    2. Use the git-appraise source code as a library. This assumes that your code is written in Go, and would consist of importing the relevant packages like this:
```go
import "github.com/google/git-appraise/review"
```

The downside of the second option is that we may need to change the package API at some point, so there is a risk that your tool could get broken unless you vendor the source code into your repo.

**Comment by cdrage** [comment]
Thanks for the clarification! I believe using git-apraise as a library would be the best fit being able to open / close github PR's from the command line. Makes sense :)

**Comment by Unknwon** [comment]
Hi @ojarjur , maybe irrelevant but similar about integration.

After read README, from what I understand is this tool keeps everything inside a specific reference such as `refs/notes/devtools/reviews` in the same repository that need to be reviewed.

Is that correct?

Thanks!

**Comment by ojarjur** [comment]
@Unknwon , yes, that is correct.

**Comment by Alsaaty** [comment]
welcome :

**Comment by ojarjur** [comment]
FYI, we know have a tool to integrate with GitHub [here](https://github.com/google/git-pull-request-mirror).

This currently one mirrors in one direction (from the pull request into git-appraise), but pull requests are welcome.

**Comment by lunny** [comment]
@Unknwon, Since Gogs is developed by Go, it can `import "github.com/google/git-appraise/review"` and use the library to integration.

**Comment by abourget** [comment]
@ojarjur put that link in the top-level README.md ! :) we need better ways to onboard people into appraise.. it's really awesome but hard to get started.  Plans for a website to show it off ?

**Comment by ojarjur** [comment]
@abourget I agree. The pull request mirror (and a bunch of other things like the rust library) need to be added to the README file. I'd welcome a pull request to add those pointers, but otherwise I'll get to it after #49 and #51 are finished and submitted.

As for a a website to show it off, I can think of two things that could be useful:

1. More end-to-end docs under the `docs/` directory (e.g. setting up the pull-request mirror or the Jenkins plugin).
2. Blog posts outlining the complete setup used by specific teams.

I'll probably get to the first eventually (but pull requests are always welcome). For the second, I'm happy to help publicize any blog posts that I find out about.
